[package]
name = "phdrs"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = { version = "0.2.94", default-features = false }

[features]
default = ["std"]
std = []
alloc = []
